### ISSUE TITLE
On click, not click release?

### ISSUE THREAD

**Issue by kodekrendel** [PygmySlowLoris/vue-ripple-directive#1]
Hi. Is there's an option to make effect when I click, not when I release click?

**Comment by hazzo** [comment]
Hi, do you mean on mouse down?

Now actually the event listener is on click. Wich envolves a mouse down and a mouse up.

If you are referring to trigger the ripple on mouse down we could look to achieve this by doing the event listener customizable.

Cheers.

**Comment by kodekrendel** [comment]
Yes, mouse down. 

You mean this:

```
        el.addEventListener('click', (event) => {
            rippler(event, el, binding.value);
        });
```
I guess if there could be options that I can customize is better then digging into the node_modules

**Comment by kodekrendel** [comment]
Also whould be nice to set time, your demo is too slow.

**Comment by hazzo** [comment]
Hi again. Thanks for the suggestion! Will do.

**Comment by Edujugon** [comment]
Hi,
We've just released a new version of the package (v1.0.6)
Now you can set the event handler by modifier.

E.g.
```
<th v-ripple.mousedown>
```

**Comment by kodekrendel** [comment]
Cool and thanks, will check out in the evening. :+1:

**Comment by Edujugon** [comment]
Great,
By the way, you can also set the transition time as modifier too.
```
<th v-ripple.mousedown.400>
```
Closing the issue now.

**Comment by kodekrendel** [comment]
@Edujugon just checked, everything working like a charm! Great plugin. Works with SSR/Nuxt. Thank you! And will waiting of more great packages :+1:

**Comment by Edujugon** [comment]
@kodekrendel Cool, happy to know it worked :)

Yeah, we are launching more packages soon.
