### ISSUE TITLE
Clicking multiple times right after each other gives a JS error

### ISSUE THREAD

**Issue by gensmann** [PygmySlowLoris/vue-ripple-directive#10]
Clicking a button multiple times right after each other gives a javascript error:

Uncaught TypeError: Cannot read property 'removeChild' of null

`
                   setTimeout(function () {
                        rippleContainer.parentNode.removeChild(rippleContainer);
                    }, 850);
  `

This is a problem if the effect is used on a button for incrementing a number or similar task where the page isn't reloaded or the click is not a simple on/off thing. :-)

**Comment by hazzo** [comment]
Hi @gensmann,

What version of ripple directive are you using? With the last version (1.0.11) this issue has being solved.
Let us know if updating solves this issue.

Thanks again!

**Comment by gensmann** [comment]
HaHa awesome, you actually fixed the issue while I was out driving. I noticed it this morning, but had to do some things before i could file the report. I was on 1.0.10.

1.0.11 works fine. Thank you, and thank you for your good work :-)
