### ISSUE TITLE
Setting global color value

### ISSUE THREAD

**Issue by luiztsmelo** [PygmySlowLoris/vue-ripple-directive#13]
How can I set the color value globally on Vue.directive?

**Comment by Edujugon** [comment]
Hi @luiztsmelo ,

For now you can provide the color you want when declaring the directive directly on each element. As explained in [the documentation.](https://github.com/PygmySlowLoris/vue-ripple-directive#sample--usage)
```
<div v-ripple="'rgba(255, 255, 255, 0.35)'"  class="button">I have different color</div>
```

Maybe we could think about adding that option for further releases.

**Comment by luiztsmelo** [comment]
It'd be a good implementation. Thanks @Edujugon.

**Comment by 274153705** [comment]
#14
