### ISSUE TITLE
On clicking of any button or image Ripple effect comes up on modal window also. because of high z-index value.

### ISSUE THREAD

**Issue by viren-singh** [PygmySlowLoris/vue-ripple-directive#15]

**Comment by hazzo** [comment]
Hi in further release will take this into consideration so z-index could be a global custom value. Such as the color implementation has been done recently. Thanks!

**Comment by viren-singh** [comment]
I have added z-index configuration and it was working fine for me. Can you please look into these pull request.

https://github.com/PygmySlowLoris/vue-ripple-directive/pull/16

**Comment by hazzo** [comment]
@viren-singh later today I'll take a look to it . If everything is fine will merge it and publish new release. Thanks!:+1:

**Comment by hazzo** [comment]
Pull request merged. Publishing new version now.
