### ISSUE TITLE
Customizable Transition Time

### ISSUE THREAD

**Issue by davevasquez** [PygmySlowLoris/vue-ripple-directive#2]
Would it be possible to adjust the transition time in some customizable way?  

I find the transition of the ripple to be a little slow for my tastes (and I suspect others might have their own personal preferences as well).  A customizable property to adjust the speed of the ripple might be very helpful in increasing this directive's popularity and reach.

**Comment by hazzo** [comment]
Hi mate. Yes I take note of this as another user suggested too. 

Thanks for contributing!

**Comment by Edujugon** [comment]
Hi,
We've just released a new version of the package (v1.0.6)
Now you can set the transition as well as the event handler by modifiers.

**Comment by davevasquez** [comment]
Excellent!!  Thanks guys!
