### ISSUE TITLE
Implement "original" ink-ripple effect

### ISSUE THREAD

**Issue by nirazul** [PygmySlowLoris/vue-ripple-directive#4]
Although the ink-ripple implementation varies slightly amongst the frameworks that use this effect, they all agree that while holding the mouse, the ripple doesn't go away.

- [material-ui (React)](http://www.material-ui.com/#/components/flat-button)
- [vue-material (Vue)](https://vuematerial.github.io/#/components/button)
- [Material UI (Webcomponents)](https://material-components-web.appspot.com/button.html)

It would be cool to have the possibility in this module aswell.

**Comment by hazzo** [comment]
Hi @Nirazul thanks for your contribution.

Now (v 1.0.8) the ripple effect by default will be trigger in `mousedown` insted of `click`. So if there is a `mousedown` event the directive will check it and if so only remove the ripple on `mouseup`. The other events to trigger the directive (ex: `mouseover`) keep working as usual, there is no hang provoked by the event.

**Comment by nirazul** [comment]
Thank you, that's great news! :)
