### ISSUE TITLE
SCRIPT1002: Syntax Error

### ISSUE THREAD

**Issue by marceloavf** [PygmySlowLoris/vue-ripple-directive#5]
First of all, thank you for the directive!

I'm getting some error in IE10 related to SCRIPT1002: Syntax Error on app.js (2122,1):

`
eval("/* harmony default export */ __webpack_exports__[\"a\"] = ({\r\n    bind: function(el, binding){\r\n\r\n        // Default values.\r\n        const props = {\r\n            event: 'mousedown',\r\n            transition: 600\r\n        };\r\n\r\n        setProps(Object.keys(binding.modifiers),props);\r\n\r\n        el.addEventListener(props.event, function(event) {\r\n            rippler(event, el, binding.value);\r\n        });\r\n\r\n        var bg = binding.value || 'rgba(0, 0, 0, 0.35)';\r\n\r\n        function rippler(event, el) {\r\n            var target = el;\r\n\r\n            // Get necessary variables\r\n            var rect        = target.getBoundingClientRect(),\r\n                left        = rect.left,\r\n                top         = rect.top,\r\n                width       = target.offsetWidth,\r\n                height      = target.offsetHeight,\r\n                dx          = event.clientX - left,\r\n                dy          = event.clientY - top,\r\n                maxX        = Math.max(dx, width - dx),\r\n                maxY        = Math.max(dy, height - dy),\r\n                style       = window.getComputedStyle(target),\r\n                radius      = Math.sqrt((maxX * maxX) + (maxY * maxY));\r\n\r\n            // Create the ripple and its container\r\n            var ripple = document.createElement(\"div\"),\r\n                rippleContainer = document.createElement(\"div\");\r\n\r\n            //Styles for ripple\r\n            ripple.style.marginTop= '0px';\r\n...
`

There is a way to fix it or disable on IE10 ?

Thanks!

**Comment by hazzo** [comment]
Hi @marceloavf thanks getting in touch with us.
Is the directive actually working? Or it does not work at all? 

I test it on  IE10 and is working fine. The only issue is that the ripple it's not being removed on 'mouseup', it seems that IE10 does not listen to that type of event, which the directive is hearing to. So it can't remove the ripple when the user takes up the finger from the click button.

**Comment by marceloavf** [comment]
It does not work at all, the page stay blank with the script error.
Could be something about IE11 emulating IE10 ?

I tried also with WindowsApp browser of Visual Studio and they keep with a blank page too.

**Comment by hazzo** [comment]
It's weird because I try to replicate this issue also emulating IE10 with IE11 and I don't get the error.
I will need more data to replicate it.

**Comment by marceloavf** [comment]
When I emulate IE10 with Edge all works fine, but it does not happen when emulate with IE11:
![image](https://user-images.githubusercontent.com/5435657/27864880-ca626f6c-6166-11e7-837c-c3cbc03f3d68.png)

The error:
![image](https://user-images.githubusercontent.com/5435657/27864935-f8c2657e-6166-11e7-8633-0b293048eaa8.png)

I implemented like this:
![image](https://user-images.githubusercontent.com/5435657/27864974-2658a99e-6167-11e7-9c1a-d670cbe6e812.png)

I'm using [vue-foundation](https://github.com/vue-foundation/vue-foundation) on my project, maybe it's something with webpack, it also happens when I run the final build.

**Comment by Edujugon** [comment]
Hi @marceloavf ,

Could you please check if your project works without our directive?
We've just tested a fresh vue-foundation app in IE10 and it breaks without even importing our directive.

In order to test it further, is there a way to have a look into your repo/project?

**Comment by marceloavf** [comment]
It works nice even in IE9 without the directive @Edujugon,

I can send you the project, but it uses an intern api to initialize.

**Comment by Edujugon** [comment]
My email is edujugon@gmail.com
Send me all the details and we'll have a look as soon as possible.

:)

**Comment by marceloavf** [comment]
I sent there, thank you!

Could be some babel config?

**Comment by marceloavf** [comment]
Going to close this since it is more/less an issue with webpack and babel configuration. If I find what's happening I'll re-open this, thanks!
