### ISSUE TITLE
console.log statement in source.

### ISSUE THREAD

**Issue by gensmann** [PygmySlowLoris/vue-ripple-directive#7]
You seem to have added a console log statement in the source in the last commit, which logs the event. Is that by purpose?

**Comment by Edujugon** [comment]
Hi @gensmann ,

Thanks for notifying about the log.
We'll check it out and remove it form the code.

**Comment by hazzo** [comment]
Hi @gensmann.

Console log has been removed from code.
Thanks for letting us know!
